# Generated by Django 5.2.6 on 2025-09-05 17:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_transacao_owner_transacao_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], default='S', max_length=1)),
                ('categoria', models.CharField(choices=[('fixa', 'Fixa'), ('variavel', 'Variável'), ('lazer', 'Lazer'), ('alimentacao', 'Alimentação'), ('outros', 'Outros')], default='fixa', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dia_vencimento', models.PositiveSmallIntegerField(help_text='Dia do mês (1–31)')),
                ('inicio', models.DateField(default=django.utils.timezone.now, help_text='Mês/ano de início')),
                ('meses', models.PositiveSmallIntegerField(default=0, help_text='Duração em meses (ex.: 6). Use 0 para indefinido.')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorrencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transacao',
            name='recorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='financas.recorrencia'),
        ),
    ]
