# Generated by Django 5.2.6 on 2025-09-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_recorrencia_transacao_recorrencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='saldo_atual',
            new_name='saldo_inicial',
        ),
        migrations.AlterField(
            model_name='recorrencia',
            name='categoria',
            field=models.CharField(choices=[('salario', 'Salário'), ('fixa', 'Fixa'), ('variavel', 'Variável'), ('lazer', 'Lazer'), ('alimentacao', 'Alimentação'), ('outros', 'Outros')], default='fixa', max_length=20),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.CharField(choices=[('salario', 'Salário'), ('fixa', 'Fixa'), ('variavel', 'Variável'), ('lazer', 'Lazer'), ('alimentacao', 'Alimentação'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
    ]
