# Generated by Django 5.2.6 on 2025-09-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_rename_saldo_atual_conta_saldo_inicial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='saldo_inicial',
        ),
        migrations.AddField(
            model_name='conta',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
