# Generated by Django 5.2.6 on 2025-10-13 01:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financas", "0005_remove_conta_saldo_inicial_conta_saldo_atual"),
    ]

    operations = [
        migrations.CreateModel(
            name="CotacaoCripto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "simbolo",
                    models.CharField(
                        db_index=True, max_length=10, verbose_name="Símbolo"
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Nome"
                    ),
                ),
                (
                    "moeda_fiat",
                    models.CharField(
                        default="USD", max_length=5, verbose_name="Moeda Fiat"
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="Preço"
                    ),
                ),
                (
                    "variacao_24h",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=7,
                        verbose_name="Variação 24h (%)",
                    ),
                ),
                (
                    "data_consulta",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Data da consulta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotação de Cripto",
                "verbose_name_plural": "Cotações de Cripto",
                "ordering": ["-data_consulta", "simbolo"],
            },
        ),
        migrations.AlterField(
            model_name="recorrencia",
            name="meses",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Duração em meses"
            ),
        ),
    ]
