# Generated by Django 5.2.6 on 2025-11-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financas", "0006_cotacaocripto_alter_recorrencia_meses"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                (
                    "valor_objetivo",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
