# Generated by Django 5.2.6 on 2025-12-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financas", "0007_metafinanceira"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autor", models.CharField(max_length=10)),
                ("texto", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
